workflow:

 url : http://localhost:9090/nifi-api/

 processors:
 
 
 #Group:DICE
  -
   name: ExtractDice XoneFICF InterestRate LST
   status: stop
   emptyQueues: false
  -
   name: ExtractDice XoneCF InterestRate OTC
   status: stop
   emptyQueues: false
  -
   name: LauncherDice 
   status: stop
   emptyQueues: false
  -
   name: SendDiceMail
   status: stop
   emptyQueues: false
  -
   name: (Manual) LauncherDice
   status: stop
   emptyQueues: false
  -
   name: ExtractDice XoneCF Credit OTC
   status: stop
   emptyQueues: false
   
   
 #Group:PRP Process
  -
   name: SendMail PRP
   status: stop
   emptyQueues: false
  -
   name: PutSFTPPropertyFile PRP
   status: stop
   emptyQueues: false
  -
   name: Gen CSV for CDV
   status: stop
   emptyQueues: false
  -
   name: ScanPrpCutOff
   status: stop
   emptyQueues: false
  -
   name: Extract CDV
   status: stop
   emptyQueues: false
  -
   name: Gen CSV for FX
   status: stop
   emptyQueues: false
  -
   name: Extract IRD
   status: stop
   emptyQueues: false
  -
   name: Extract FID
   status: stop
   emptyQueues: false
  -
   name: SendPRPMail
   status: stop
   emptyQueues: false
  -
   name: (Manual Mode) Exec PRP Process
   status: stop
   emptyQueues: false
  -
   name: Gen CSV for IRD
   status: stop
   emptyQueues: false
  -
   name: Gen CSV for FID
   status: stop
   emptyQueues: false
  -
   name: Extract FX
   status: stop
   emptyQueues: false
  
  
 #Group:MIFID Meteor
  -
   name: MifidEligibility
   status: stop
   emptyQueues: false
  -
   name: SendMail MIFID Meteor
   status: stop
   emptyQueues: false
   
   
 #Group:MI Integration
  -
   name: MIDataIntegration ONE
   status: stop
   emptyQueues: false
  -
   name: FileWatcherProcess IPM
   status: stop
   emptyQueues: false
  -
   name: SendMail MI Integration
   status: stop
   emptyQueues: false
  -
   name: SendMILoadedMessage IPM
   status: stop
   emptyQueues: false
  -
   name: ManualDBExtractLaunch MI
   status: stop
   emptyQueues: false
  -
   name: AutoDBExtractLaunch MI IPM
   status: stop
   emptyQueues: false
  -
   name: FileWatcherProcess ONE
   status: stop
   emptyQueues: false
  -
   name: SendMIPairingMessage
   status: stop
   emptyQueues: false
  -
   name: AutoDBExtractLaunch MI ONE
   status: stop
   emptyQueues: false
  -
   name: SendMILoadedMessage ONE
   status: stop
   emptyQueues: false
  -
   name: MIDataIntegration IPM
   status: stop
   emptyQueues: false
   
   
 #Group:TECH HISTO
  -
   name: ScanTechCutOff
   status: stop
   emptyQueues: false
  -
   name: Move Data 
   status: stop
   emptyQueues: false
  -
   name: Finalize historization 
   status: stop
   emptyQueues: false
  -
   name: Definition of the scope in TPS_DWH$OWNER
   status: stop
   emptyQueues: false
  -
   name: Purge Data 
   status: stop
   emptyQueues: false
  -
   name: (Manual) ScanTechCutOff
   status: stop
   emptyQueues: false
  -
   name: Create PK constraints 
   status: stop
   emptyQueues: false
  -
   name: SendMail TECH
   status: stop
   emptyQueues: false
  -
   name: Drop PK constraints of TPS_HISTO$OWNER
   status: stop
   emptyQueues: false
  -
   name: Gather Oracle statistics
   status: stop
   emptyQueues: false
   
 #Group:OTC Refactoring Scope
  -
   name: Send CSV File to FTR
   status: stop
   emptyQueues: false
  -
   name: EndRequest
   status: stop
   emptyQueues: false
  -
   name: Generate CSV flow
   status: stop
   emptyQueues: false
  -
   name: Store CSV File to archive server OTC
   status: stop
   emptyQueues: false
   
   
 #Group:FCCR
  -
   name: One Month OTC
   status: stop
   emptyQueues: false
  -
   name: PutSFTPPropertyFile Sentinel
   status: stop
   emptyQueues: false
  -
   name: Truncate tables
   status: stop
   emptyQueues: false
  -
   name: One Month LST P3
   status: stop
   emptyQueues: false
  -
   name: ExtractSentinel
   status: stop
   emptyQueues: false
  -
   name: SendMail FCCR
   status: stop
   emptyQueues: false
  -
   name: ExtractIndigo
   status: stop
   emptyQueues: false
  -
   name: PutSFTPPropertyFile Indigo+FCCR
   status: stop
   emptyQueues: false
  -
   name: Insert LST PART 2
   status: stop
   emptyQueues: false
  -
   name: SendMail FCCR One Month
   status: stop
   emptyQueues: false
  -
   name: ExtractFccr MARKET
   status: stop
   emptyQueues: false
  -
   name: DayOfMonthReached
   status: stop
   emptyQueues: false
  -
   name: ScanFilesToSend
   status: stop
   emptyQueues: false
  -
   name: ScanTechCutOffFCCR
   status: stop
   emptyQueues: false
  -
   name: Insert FXS
   status: stop
   emptyQueues: false
  -
   name: Insert FIN
   status: stop
   emptyQueues: false
  -
   name: (Manual) ScanFCCRCutOff One Month
   status: stop
   emptyQueues: false
  -
   name: ExtractFccr NON MARKET
   status: stop
   emptyQueues: false
  -
   name: Insert OTC
   status: stop
   emptyQueues: false
  -
   name: One Month LST P2
   status: stop
   emptyQueues: false
  -
   name: (Manual) ScanTechCutOff FCCR
   status: stop
   emptyQueues: false
  -
   name: One Month LST P1
   status: stop
   emptyQueues: false
  -
   name: Truncate tables One Month
   status: stop
   emptyQueues: false
  -
   name: (Manual) ScanFCCRCutOff One Month P2
   status: stop
   emptyQueues: false
  -
   name: Insert LST Part 1
   status: stop
   emptyQueues: false
  
  
 #Group:SGBT RiskExec
  -
   name: ORMGenXml
   status: stop
   emptyQueues: false
  -
   name: ORMValidateGenXml
   status: stop
   emptyQueues: false
  -
   name: SgbtRiskExecSnapshotAggregator
   status: stop
   emptyQueues: false
  -
   name: ORMJsonLog
   status: stop
   emptyQueues: false
  -
   name: ORMCreateZipXml
   status: stop
   emptyQueues: false
  -
   name: ORMFetchData
   status: stop
   emptyQueues: false
  -
   name: PutSFTPPropertyFile RiskExec
   status: stop
   emptyQueues: false
  -
   name: ORMPerimeter
   status: stop
   emptyQueues: false
  -
   name: ManualDBExtractLaunch SGBT
   status: stop
   emptyQueues: false
   
   
 #Group:NiFi Flow
  -
   name: SendSnapshotGeneratedMessage
   status: stop
   emptyQueues: false
  -
   name: SendMail PRP ECL
   status: stop
   emptyQueues: false
  -
   name: SendMail OTC Refacto
   status: stop
   emptyQueues: false
  -
   name: DBCapacityMonitoring
   status: stop
   emptyQueues: false
  -
   name: ScanMessage
   status: stop
   emptyQueues: false
   
   
 #Group:ECL
  -
   name: Put Pivot File To FTR
   status: stop
   emptyQueues: false
  -
   name: FileWatcherProcess ECL
   status: stop
   emptyQueues: false
  -
   name: EclFileIntegration
   status: stop
   emptyQueues: false
  -
   name: Store CSV File to archive server ECL
   status: stop
   emptyQueues: false
  -
   name: SendMail ECL
   status: stop
   emptyQueues: false
   
   
 #Group:DQI Completeness
  -
   name: DQIExtractTps
   status: stop
   emptyQueues: false
  -
   name: FileWatcherProcess DQI
   status: stop
   emptyQueues: false
  -
   name: PutSFTPPropertyFile DQI
   status: stop
   emptyQueues: false
  -
   name: GenExtractCSV DQI
   status: stop
   emptyQueues: false
  -
   name: DQICompareCps
   status: stop
   emptyQueues: false
   
   
 #Group:Snapshot Execution
  -
   name: SendMail Snapshot
   status: stop
   emptyQueues: false
  -
   name: Snapshot Scope Calculation
   status: stop
   emptyQueues: false
  -
   name: RequestIdSwitch
   status: stop
   emptyQueues: false
  -
   name: Scan Snapshots Cut Off
   status: stop
   emptyQueues: false
  -
   name: (Manual) Launch SnapShot
   status: stop
   emptyQueues: false
  -
   name: Insert Exception Log
   status: stop
   emptyQueues: false
   
   
 #Group:GOLD
  -
   name: Trigger GOLD Position to DWH
   status: stop
   emptyQueues: false
  -
   name: ExecSQL Trade to DWH
   status: stop
   emptyQueues: false
  -
   name: Trigger GOLD Pivot Trade
   status: stop
   emptyQueues: false
  -
   name: ExecSQL Pivot Trade
   status: stop
   emptyQueues: false
  -
   name: Trigger GOLD Trade to DWH
   status: stop
   emptyQueues: false
  -
   name: ExecSQL Purge Pivot
   status: stop
   emptyQueues: false
  -
   name: ExecSQL Position to DWH
   status: stop
   emptyQueues: false
  -
   name: Trigger GOLD Purge Pivot
   status: stop
   emptyQueues: false
  -
   name: Trigger GOLD Pivot Position
   status: stop
   emptyQueues: false
  -
   name: ExecSQL Pivot Position
   status: stop
   emptyQueues: false
